# Generated by Django 5.2.8 on 2026-01-10 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0014_tbl_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_replacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replacement_code', models.IntegerField(null=True)),
                ('replacement_sino', models.IntegerField(null=True)),
                ('replacement_qty', models.IntegerField(null=True)),
                ('replacement_voltage', models.IntegerField(null=True)),
                ('replacemant_ampere', models.IntegerField(null=True)),
                ('replacement_app', models.CharField(max_length=50)),
                ('replacement_period', models.IntegerField(null=True)),
                ('replacement_complaint', models.CharField(max_length=50)),
                ('replacement_status', models.IntegerField(default=0)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_request')),
            ],
        ),
    ]
