# Generated by Django 5.2.8 on 2026-01-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_replacement',
            name='replacement_status',
            field=models.CharField(max_length=50),
        ),
    ]
