# Generated by Django 5.2.8 on 2026-01-17 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0002_alter_tbl_replacement_replacement_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_replacement',
            old_name='replacemant_ampere',
            new_name='replacement_ampere',
        ),
    ]
