# Generated by Django 5.2.8 on 2026-01-23 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0003_rename_replacemant_ampere_tbl_replacement_replacement_ampere'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_replacement',
        ),
    ]
