# Generated by Django 5.2.8 on 2026-01-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_replacement',
            name='replacement_period',
            field=models.CharField(null=True),
        ),
    ]
