# Generated by Django 5.2.8 on 2026-01-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0006_alter_tbl_replacement_replacement_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_replacement',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='tbl_replacement',
            name='signature',
        ),
        migrations.AddField(
            model_name='tbl_replacement',
            name='replacement_pdf',
            field=models.FileField(null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='tbl_replacement',
            name='replacement_signature',
            field=models.ImageField(null=True, upload_to='signatures/'),
        ),
    ]
