# Generated by Django 5.2.8 on 2025-11-27 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_subcategory'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_servicecentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicecentre_name', models.CharField(max_length=50)),
                ('servicecentre_details', models.CharField(max_length=50)),
                ('servicecentre_address', models.CharField(max_length=50)),
                ('servicecentre_photo', models.FileField(upload_to='Assets/scDocs/')),
                ('servicecentre_proof', models.FileField(upload_to='Assets/scDocs/')),
                ('servicecentre_contact', models.CharField(max_length=50)),
                ('servicecentre_email', models.CharField(max_length=50)),
                ('servicecentre_password', models.CharField(max_length=50)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
