# Generated by Django 5.2.8 on 2025-11-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_tbl_servicecentre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_servicecentre',
            name='servicecentre_photo',
            field=models.FileField(upload_to='Assets/ScDocs/'),
        ),
        migrations.AlterField(
            model_name='tbl_servicecentre',
            name='servicecentre_proof',
            field=models.FileField(upload_to='Assets/ScDocs/'),
        ),
    ]
