# Generated by Django 5.2.8 on 2025-11-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_alter_tbl_servicecentre_servicecentre_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_servicecentre',
            name='servicecentre_status',
            field=models.IntegerField(default=0),
        ),
    ]
