# Generated by Django 5.2.8 on 2026-01-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_delete_tbl_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='user_mobile',
            field=models.CharField(null=True),
        ),
    ]
