# Generated by Django 5.2.8 on 2025-12-06 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0005_tbl_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=50)),
                ('worker_email', models.CharField(max_length=50)),
                ('worker_contact', models.CharField(max_length=50)),
                ('worker_address', models.CharField(max_length=50)),
                ('worker_photo', models.FileField(upload_to='Assets/WDocs/')),
                ('worker_password', models.CharField(max_length=50)),
                ('worker_status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
