# Generated by Django 5.2.8 on 2025-12-06 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_delete_tbl_worker'),
        ('ServiceCentre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_worker',
            name='servicecentre_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_servicecentre'),
        ),
    ]
