# Generated by Django 5.2.8 on 2025-12-19 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0006_delete_tbl_worker'),
        ('ServiceCentre', '0002_tbl_worker_servicecentre_id'),
        ('User', '0002_delete_tbl_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.CharField(max_length=50)),
                ('request_todate', models.CharField(max_length=50)),
                ('request_details', models.CharField(max_length=50)),
                ('request_status', models.CharField(max_length=50)),
                ('request_amount', models.CharField(max_length=50)),
                ('request_emergency', models.CharField(max_length=50)),
                ('servicecentre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_servicecentre')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceCentre.tbl_worker')),
            ],
        ),
    ]
