# Generated by Django 5.2.8 on 2025-12-19 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_request',
            old_name='servicecentre_id',
            new_name='servicecentre',
        ),
        migrations.RenameField(
            model_name='tbl_request',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='tbl_request',
            old_name='worker_id',
            new_name='worker',
        ),
    ]
