# Generated by Django 5.2.8 on 2025-12-19 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCentre', '0002_tbl_worker_servicecentre_id'),
        ('User', '0004_rename_servicecentre_id_tbl_request_servicecentre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_request',
            name='request_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tbl_request',
            name='request_emergency',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tbl_request',
            name='request_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tbl_request',
            name='request_todate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tbl_request',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ServiceCentre.tbl_worker'),
        ),
    ]
