# Generated by Django 5.2.8 on 2025-12-31 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_tbl_request_request_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_request',
            name='request_emdetails',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
