# Generated by Django 5.2.8 on 2025-12-31 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_delete_tbl_worker'),
        ('User', '0006_tbl_request_request_emdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_request',
            name='servicecentre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_servicecentre'),
        ),
    ]
