# Generated by Django 5.2.8 on 2026-01-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_tbl_request_servicecentre'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_request',
            name='product_bill',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='tbl_request',
            name='product_photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
