# Generated by Django 5.2.8 on 2026-01-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_tbl_request_product_bill_tbl_request_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_request',
            name='request_todate',
            field=models.DateField(null=True),
        ),
    ]
