# Generated by Django 5.2.8 on 2026-01-09 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_delete_tbl_worker'),
        ('User', '0009_alter_tbl_request_request_todate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_request',
            name='product_bill',
            field=models.FileField(null=True, upload_to='Assets/UDocs/'),
        ),
        migrations.AlterField(
            model_name='tbl_request',
            name='product_photo',
            field=models.FileField(null=True, upload_to='Assets/UDocs/'),
        ),
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_content', models.CharField(max_length=50)),
                ('complaint_date', models.DateField(auto_now_add=True)),
                ('complaint_reply', models.CharField(max_length=50)),
                ('complaint_status', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
