# Generated by Django 5.2.8 on 2026-01-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_alter_tbl_request_product_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_complaint',
            name='complaint_title',
            field=models.CharField(null=True),
        ),
    ]
