# Generated by Django 5.2.8 on 2026-01-09 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_tbl_complaint_complaint_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_complaint',
            old_name='user_id',
            new_name='user',
        ),
    ]
