# Generated by Django 5.2.8 on 2026-01-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_rename_user_id_tbl_complaint_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_complaint',
            name='complaint_content',
            field=models.CharField(null=True),
        ),
    ]
