# Generated by Django 5.2.8 on 2026-01-09 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_delete_tbl_worker'),
        ('User', '0013_alter_tbl_complaint_complaint_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_content', models.CharField(null=True)),
                ('rating_value', models.CharField(null=True)),
                ('rating_datetime', models.DateField(auto_now_add=True)),
                ('servicecentre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_servicecentre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
