# Generated by Django 5.2.8 on 2026-01-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_tbl_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_request',
            name='request_starttime',
            field=models.DateTimeField(null=True),
        ),
    ]
