# Generated by Django 5.2.8 on 2026-01-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_tbl_request_request_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_request',
            name='request_endtime',
            field=models.DateTimeField(null=True),
        ),
    ]
