# Generated by Django 5.2.8 on 2026-01-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_tbl_request_request_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_complaint',
            name='complaint_reply',
            field=models.CharField(null=True),
        ),
    ]
