# Generated by Django 5.2.8 on 2026-01-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_alter_tbl_complaint_complaint_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_request',
            name='request_workendtime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tbl_request',
            name='request_workstarttime',
            field=models.DateTimeField(null=True),
        ),
    ]
