# Generated by Django 5.2.8 on 2026-01-30 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_tbl_user_user_mobile'),
        ('ServiceCentre', '0002_tbl_worker_servicecentre_id'),
        ('User', '0018_tbl_request_request_workendtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_content', models.CharField(max_length=500)),
                ('chat_time', models.DateTimeField()),
                ('chat_file', models.FileField(upload_to='ChatFiles/')),
                ('user_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to='Guest.tbl_user')),
                ('user_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to='Guest.tbl_user')),
                ('worker_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist_from', to='ServiceCentre.tbl_worker')),
                ('worker_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist_to', to='ServiceCentre.tbl_worker')),
            ],
        ),
    ]
