# Generated by Django 5.2.8 on 2026-01-30 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCentre', '0002_tbl_worker_servicecentre_id'),
        ('User', '0019_tbl_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_chat',
            name='worker_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_from', to='ServiceCentre.tbl_worker'),
        ),
        migrations.AlterField(
            model_name='tbl_chat',
            name='worker_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_to', to='ServiceCentre.tbl_worker'),
        ),
    ]
