# Generated by Django 5.2.8 on 2026-01-30 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0020_alter_tbl_chat_worker_from_alter_tbl_chat_worker_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_rating',
        ),
    ]
